<!DOCTYPE html>

    <style> 
    html{   
                background-color:yellow;
                font-size: 60px; 
                font-family: Inverted Square; 

    }
    form{
        font-size: 60px;
        font-family: inverted Square;
    }
    button {
        font-size: 40px;
    }
    input {
        font-size: 40px;
    }
    </style> 


</head>
<center>
<body><h1> The Lost Samsung Phone Acore 4 </h3>
<hr>
<br>
        <p> The thing that is gone is not suppose to be gone so I will have to make due with the technology, that I 
        able too, so I was able to not use any other phone but the other one. This include iPhone 4 and iPhone 6plus 
        in order to just get the manager. to use Whatapps and contact me, for later but I was going to work, the building 
        next door came based on the be build't but because of it I was not ready to admit that it wa lost.'</p>
        <br>
        <img src = "https://user-images.githubusercontent.com/87011258/170230377-b73defac-296b-4480-a57f-c48abb50aee9.png"/> 
        <br> 
        <h3> The best thing Samsung Acore 4</h3>
        <hr>
        <p> Enjoy peace of mind when you choose to buy a Galaxy smartphone. The Interactive 
        diagnostics and optimization on Samsung Members app makes it easy to tune up the 
        performance of your devices, while our helpline lets you troubleshoot problems when 
        you need extra assistance. </p>
        <img src = " https://th.bing.com/th/id/R.a2497eceb5391f11e47e5df10b8faa97?rik=kBVgIlcM1klWrA&pid=ImgRaw&r=0"/>
</body>
        <p> The other thing would be that I would like to find out why it is going on for a long time on order to 
        not get to my hands otherwise I may have just put the phone in the wrong place in order to make sure that 
        it is dafe but I hope the poeple in the following list below must not have it or they should give it 
        to me before I think it is the company. </p> 
</center>
        <li> Tshireletso </li>
        <li> Bianca </li>
        <li> Itebogeng </li> 
        <li> Tumelo </li>
        <li> Gugguletho - SeaGate. </li>
        <br>
        <h3> If you find the it (fill in below) </h3>
        <hr>
        <form action="/html/tags/html_form_tag_action.cfm" method="get" target="_blank">
        First name:
    <input type="text" name="first_name" maxlength="100">
        <br />
    Last name:
    <input type="text" name="last_name" maxlength="100">
    <br><br><Br>
    <button type="submit">Submit</button>
    </form>


    
    </select>
<cite> Copyright 2019 </cite>
<cite> Property of Bill Gate..</cite>
</html>
